package main

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"flag"
	"fmt"
	"io"
	"log"
	"os"
	"path/filepath"
	"runtime"
	"runtime/debug"
	"strings"
	"sync"

	"github.com/noumena-labs-llc/personal-mcp-server/internal/atomicfile"
	"github.com/noumena-labs-llc/personal-mcp-server/internal/config"
)

var (
	binarySHA256Once sync.Once
	binarySHA256     string
)

func initConfig(args []string) {
	if len(args) > 0 && isHelpArg(args[0]) {
		printCommandHelp("init")
		return
	}
	fs := flag.NewFlagSet("init", flag.ExitOnError)
	configPath := fs.String("config", defaultConfigPath(), "where to write config.toml")
	root := fs.String("root", ".", "allowed root directory")
	force := fs.Bool("force", false, "overwrite existing config")
	generateTokenFlag := fs.Bool("generate-token", false, "write a token file and configure auth_token_file")
	tokenPath := fs.String("token-file", defaultTokenPath(), "where to write generated token")
	_ = fs.Parse(args)

	absRoot, err := filepath.Abs(*root)
	if err != nil {
		log.Fatal(err)
	}
	if _, err := os.Stat(absRoot); err != nil {
		log.Fatalf("root: %v", err)
	}
	if _, err := os.Stat(*configPath); err == nil && !*force {
		log.Fatalf("config already exists: %s (use --force to overwrite)", *configPath)
	}
	if err := os.MkdirAll(filepath.Dir(*configPath), 0o700); err != nil {
		log.Fatal(err)
	}
	tokenConfigPath := ""
	if *generateTokenFlag {
		if err := os.MkdirAll(filepath.Dir(*tokenPath), 0o700); err != nil {
			log.Fatal(err)
		}
		tok, err := generateToken()
		if err != nil {
			log.Fatal(err)
		}
		if _, err := os.Stat(*tokenPath); err == nil && !*force {
			log.Fatalf("token file already exists: %s (use --force to overwrite)", *tokenPath)
		}
		if err := atomicfile.WriteFile(*tokenPath, []byte(tok+"\n"), 0o600); err != nil {
			log.Fatal(err)
		}
		tokenConfigPath = *tokenPath
		fmt.Printf("wrote %s\n", *tokenPath)
	}
	content := starterConfig(absRoot, tokenConfigPath)
	if err := atomicfile.WriteFile(*configPath, []byte(content), 0o600); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("wrote %s\n", *configPath)
	if !*generateTokenFlag {
		fmt.Println("set PERSONAL_MCP_TOKEN before running serve or doctor, or re-run init with --generate-token")
	}
}

func defaultAppRoot() string {
	if root := strings.TrimSpace(os.Getenv("PERSONAL_MCP_ROOT")); root != "" {
		return expandUserPath(root)
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return filepath.Join(".", ".personal-mcp-server")
	}
	return filepath.Join(home, ".personal-mcp-server")
}

func defaultConfigDir() string {
	return filepath.Join(defaultAppRoot(), "config")
}

func defaultConfigPath() string {
	return filepath.Join(defaultConfigDir(), "config.toml")
}

func defaultTokenPath() string {
	return filepath.Join(defaultConfigDir(), "token")
}

func defaultTrustStorePath() string {
	return filepath.Join(defaultConfigDir(), "trusted-projects.toml")
}

func defaultBinaryPath() string {
	return filepath.Join(defaultAppRoot(), "bin", "personal-mcp-server")
}

func starterConfig(root, tokenFile string) string {
	root = strings.ReplaceAll(root, "\\", "\\\\")
	authLine := `auth_token_env = "PERSONAL_MCP_TOKEN"`
	if tokenFile != "" {
		tokenFile = strings.ReplaceAll(tokenFile, "\\", "\\\\")
		authLine = fmt.Sprintf("auth_token_file = %q", tokenFile)
	}
	return fmt.Sprintf(`# Generated by personal-mcp-server init.
config_version = 1
roots = [%q]

[defaults]
# Optional single-user convenience mode. Explicit settings below still win.
allow_everything = false

[server]
host = "127.0.0.1"
port = 3929
endpoint = "/mcp"
%s
validate_origin = true
allowed_origins = ["http://127.0.0.1", "http://localhost"]

[server_logging]
# Diagnostic server logs. Audit logs remain separate.
# When path is set, diagnostics go to the file; error-level diagnostics are also duplicated to stderr.
# Rotated files are kept as server.log.1, server.log.2, and so on.
level = "info"
path = ""
max_bytes = 10485760
max_backups = 5
tool_slow_ms = 3000
tool_very_slow_ms = 10000

[audit]
# Optional. If omitted, audit logs go to stderr unless --audit-log is provided.
path = ""
max_bytes = 10485760
max_backups = 5

[feedback]
# Local-only feedback collection. feedback_submit appends JSONL here and never sends network data.
enabled = true
path = "~/.personal-mcp-server/feedback/feedback.jsonl"
max_summary_bytes = 500
max_details_bytes = 4000
max_context_bytes = 12000

[project_configs]
enabled = true
filename = ".personal-mcp-server.toml"
auto_load = false
trust_store = %q

# max_write_bytes is retained for config compatibility; write/delete/move tools no longer use it as a gate.
[limits]
max_read_bytes = 200000
max_write_bytes = 50000
max_search_results = 100
max_search_file_bytes = 1000000
command_timeout_seconds = 20
max_command_output_bytes = 200000
diff_context_lines = 3
max_diff_bytes = 200000
max_patch_bytes = 200000

[secrets]
deny_names = [".env", ".env.local", ".env.production", "id_rsa", "id_ed25519", "credentials", "known_hosts"]
deny_extensions = [".pem", ".key", ".p12", ".pfx"]

[tools.fs_list_roots]
enabled = true
[tools.fs_list_dir]
enabled = true
[tools.fs_get_file_info]
enabled = true
[tools.fs_tail_file]
enabled = true
[tools.fs_read_file]
enabled = true
[tools.fs_search_text]
enabled = true
[tools.fs_find]
enabled = true
[tools.fs_tree]
enabled = true
[tools.fs_replace_regex]
enabled = false
[tools.fs_apply_patch]
enabled = false
[tools.fs_edit_lines]
enabled = false
[tools.fs_apply_unified_patch]
enabled = false
[tools.fs_create_file]
enabled = false
[tools.fs_create_dir]
enabled = false
[tools.fs_replace_file]
enabled = false
[tools.fs_delete_file]
enabled = false
[tools.fs_delete_files]
enabled = false
[tools.fs_move_file]
enabled = false
[tools.fs_append_file]
enabled = false
[tools.md_outline]
enabled = true
[tools.md_read_section]
enabled = true
[tools.md_replace_section]
enabled = false
[tools.md_insert_section]
enabled = false
[tools.md_append_section]
enabled = false
[tools.json_outline]
enabled = true
[tools.json_keys]
enabled = true
[tools.json_get]
enabled = true
[tools.json_slice]
enabled = true
[tools.json_search]
enabled = true
[tools.json_validate]
enabled = true
[tools.jsonl_info]
enabled = true
[tools.jsonl_read]
enabled = true
[tools.jsonl_tail]
enabled = true
[tools.jsonl_filter]
enabled = true
[tools.jsonl_validate]
enabled = true
[tools.feedback_submit]
enabled = true
[tools.diagnostics_recent_slow_tools]
enabled = true
[tools.config_validate]
enabled = true
[tools.config_explain]
enabled = true
[tools.git_diff]
enabled = true
[tools.git_status]
enabled = true
[tools.cmd_run_named]
enabled = false
[tools.cmd_run_sequence]
enabled = false
[tools.cmd_run_argv]
enabled = false
[tools.server_info]
enabled = true
[tools.policy_describe]
enabled = true
[tools.project_info]
enabled = true
[tools.workflow_list]
enabled = true
[tools.project_config_describe]
enabled = true
[tools.setup_guide]
enabled = true
[tools.guide_list]
enabled = true
[tools.guide_read]
enabled = true
[tools.cmd_explain_policy]
enabled = true
[tools.file_explain_policy]
enabled = true
[tools.resource_list]
enabled = true
[tools.resource_read]
enabled = true

[approval]
enabled = true
timeout_seconds = 120
default_on_timeout = "deny"
remember_session_decisions = false

[file_policy]
read_default = "allow"
write_default = "deny"
create_default = "prompt"
patch_default = "prompt"
unified_patch_default = "prompt"

[[file_policy.rules]]
name = "deny secrets"
action = "deny"
operations = ["read", "list", "info", "search", "patch", "create", "write"]
pattern = "(^|/)(\\.env|id_rsa|id_ed25519|credentials)(\\.|$|/)"

[command_environment]
# Direct argv is the default. Enable persistent shells only when trusted project commands need interactive shell setup.
allow_persistent_shell = false
allowed_shells = ["/bin/zsh", "/bin/bash"]
persistent_shell_pool_size = 2
persistent_shell_acquire_timeout_seconds = 6
persistent_shell_quiet_period_ms = 1000
persistent_shell_startup_timeout_seconds = 30

[command_policy]
default = "deny"

[[command_policy.rules]]
name = "allow git read-only"
action = "allow"
exec = "git"
subcommands = ["status", "diff", "log", "show", "branch"]

[[command_policy.rules]]
name = "prompt other git commands"
action = "prompt"
exec = "git"
args_regex = ".*"

[[commands]]
name = "git-status"
exec = "git"
args = ["status", "--short"]
description = "Show concise working tree status."

[[commands]]
name = "git-log"
exec = "git"
args = ["log", "--oneline", "-20"]
description = "Show recent commits."

[[commands]]
name = "git-add-all"
exec = "git"
args = ["add", "."]
description = "Stage all changes under the current repository path."

[[commands]]
name = "git-commit"
exec = "git"
args = ["commit", "--verbose"]
description = "Create a commit from staged changes. This may fail if no commit message is supplied by Git configuration. Prefer cmd_run_argv for commit messages when policy allows it."

[prompts.safe_code_edit]
enabled = true
description = "Safely inspect, patch, and verify code inside allowed roots."
template = """
Use personal MCP server carefully. Start by calling tool_catalog_batch and policy_describe. If resources are visible, read personal-mcp://server, personal-mcp://policy, and personal-mcp://guide/tools; otherwise call guide_list and guide_read first. Work only inside configured roots. Prefer resources for read-only context when available. Search before reading broadly. For large files, never request whole_file=true unless the user explicitly needs the entire file; prefer fs_get_file_info, fs_tail_file, fs_search_text, and fs_read_file with start_line/max_lines. Set fs_get_file_info count_lines=true when a workflow needs an exact line count. Only global config can raise max_read_bytes. Use fs_edit_lines for line-number anchored edits, fs_apply_patch for scoped text edits, or fs_apply_unified_patch for unified diffs; review fs_apply_patch warnings when found counts differ and re-read before retrying zero-match edits. After edits, use git_diff and an allowed verification command when available. If approval is required, explain why and ask the local user to use personal-mcp-server approvals watch/list plus approve/deny; no native OS dialog is shown.
"""

[prompts.inspect_project]
enabled = true
description = "Read-only project inspection workflow."
template = """
Inspect the project without modifying files. Call tool_catalog_batch and policy_describe first. Use resources such as personal-mcp://roots, personal-mcp://policy, and personal-mcp://guide/tools when available; otherwise call guide_list and guide_read. Use fs_list_dir, fs_search_text, fs_get_file_info, and fs_read_file as needed. Do not call fs_edit_lines, fs_apply_patch, fs_create_file, fs_replace_file, fs_delete_file, fs_delete_files, fs_move_file, fs_create_dir, cmd_run_named, cmd_run_sequence, or cmd_run_argv.
"""

[prompts.edit_and_verify]
enabled = true
description = "Make a scoped edit, show the diff, and run configured verification commands."
template = """
Inspect relevant files after calling tool_catalog_batch. If resources are visible, read personal-mcp://guide/tools; otherwise call guide_list and guide_read. Apply the intended line-based or scoped edit, then review git_diff and run an available named or policy-allowed verification command. Use dry_run only when a preview is useful. Treat fs_apply_patch warnings as review signals and retry zero-match edits only after re-reading. If a command or file operation requires approval, explain why it is needed and ask the local user to use personal-mcp-server approvals watch/list plus approve/deny.
"""
`, root, authLine, strings.ReplaceAll(defaultTrustStorePath(), "\\", "\\\\"))
}

func generateToken() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(b), nil
}

func checkTokenFilePermissions(path string) {
	info, err := os.Stat(path)
	if err != nil {
		fmt.Printf("auth token file permissions: WARN: %v\n", err)
		return
	}
	if runtime.GOOS != "windows" && info.Mode().Perm()&0o077 != 0 {
		fmt.Printf("auth token file permissions: WARN: %s is readable by group or others (%s)\n", path, info.Mode().Perm())
		return
	}
	fmt.Println("auth token file permissions: ok")
}

func printVersion() {
	fmt.Println("personal-mcp-server " + version)
	fmt.Println("go: " + runtime.Version())
	fmt.Println("mcp-go-sdk: " + mcpSDKVersion())
}

func mcpSDKVersion() string {
	if bi, ok := debug.ReadBuildInfo(); ok {
		for _, dep := range bi.Deps {
			if dep.Path == "github.com/modelcontextprotocol/go-sdk" {
				return dep.Version
			}
		}
	}
	return "unknown"
}

func serverInfo(cfg *config.Config) map[string]any {
	largeFileGuidance := []string{
		"Do not request whole_file=true unless the user explicitly needs the entire file.",
		"Use fs_search_text to locate relevant sections before reading.",
		"Use fs_read_file with start_line and max_lines for large files.",
		"Use fs_get_file_info to check size before reading unfamiliar files.",
		"If a file exceeds max_read_bytes, avoid whole-file retries; raise limits.max_read_bytes only in the global config and verify with policy_describe.",
	}
	if cfg.Tools.Find.Enabled {
		largeFileGuidance[1] = "Use fs_find and fs_search_text to locate relevant sections before reading."
	}
	return map[string]any{
		"name":           "personal-mcp-server",
		"version":        version,
		"binary_sha256":  runtimeBinarySHA256(),
		"module":         "github.com/noumena-labs-llc/personal-mcp-server",
		"transport":      "streamable_http",
		"protocol":       "mcp",
		"go_version":     runtime.Version(),
		"mcp_go_sdk":     mcpSDKVersion(),
		"config_version": cfg.ConfigVersion,
		"features": map[string]bool{
			"hot_reload":                true,
			"localhost_only":            true,
			"allow_everything_defaults": cfg.Defaults.AllowEverything,
			"resources":                 true,
			"tool_resource_mirror":      true,
			"file_policy":               true,
			"command_policy":            true,
			"approvals":                 cfg.Approval.Enabled,
			"per_call_cwd":              true,
			"unified_patch":             cfg.Tools.ApplyUnifiedPatch.Enabled,
			"regex_replace":             cfg.Tools.ReplaceRegex.Enabled,
			"native_find":               cfg.Tools.Find.Enabled,
			"guide_tools":               true,
			"git_status":                cfg.Tools.GitStatus.Enabled || cfg.Tools.GitDiff.Enabled,
			"bounded_reads_default":     true,
			"project_configs":           cfg.ProjectConfigs.Enabled,
			"background_jobs":           cfg.Tools.RunCommand.Enabled,
			"server_logging":            true,
			"tool_latency_logging":      true,
			"progressive_catalog":       true,
			"json_navigation":           cfg.Tools.JSONOutline.Enabled || cfg.Tools.JSONGet.Enabled || cfg.Tools.JSONKeys.Enabled || cfg.Tools.JSONSlice.Enabled || cfg.Tools.JSONSearch.Enabled,
			"jsonl_navigation":          cfg.Tools.JSONLInfo.Enabled || cfg.Tools.JSONLRead.Enabled || cfg.Tools.JSONLTail.Enabled || cfg.Tools.JSONLFilter.Enabled,
			"feedback_collection":       cfg.Feedback.Enabled && cfg.Tools.FeedbackSubmit.Enabled,
		},
		"large_file_guidance": largeFileGuidance,
		"tool_latency": map[string]any{
			"slow_ms":      cfg.ServerLogging.ToolSlowMS,
			"very_slow_ms": cfg.ServerLogging.ToolVerySlowMS,
		},
	}
}

func runtimeBinarySHA256() string {
	binarySHA256Once.Do(func() {
		path, err := os.Executable()
		if err != nil {
			binarySHA256 = ""
			return
		}
		file, err := os.Open(path) //nolint:gosec // hashes the current local executable selected by the runtime.
		if err != nil {
			binarySHA256 = ""
			return
		}
		defer func() { _ = file.Close() }()

		sum := sha256.New()
		if _, err := io.Copy(sum, file); err != nil {
			binarySHA256 = ""
			return
		}
		binarySHA256 = hex.EncodeToString(sum.Sum(nil))
	})
	return binarySHA256
}
